### ISSUE TITLE
Series meta information being displayed twice only on the series archive pages

### ISSUE THREAD

**Issue by brandenm2** [roughsmoothengine/organize-series#26]
This is just a small aesthetic problem, but when I click a series in the series widget to go to that series’ archive page (the page where it lists all the posts from that series together), it displays the series meta information twice.

So for example, it will say at the top of each post in the series (but with the respective name and numbers for each post):

This entry is part 1 of 5 in the series…
This entry is part 1 of 5 in the series…

When clicking to go into an individual post, it still properly displays the meta information only once.

Disabling the series meta information removes all traces of it both from the series archive page and the individual posts.

I can’t remember, but I may have noticed this problem a long time ago as well. I can’t say for sure though if this only started at a certain time or not.

Any thoughts? Thanks.

p.s. I copy pasted this from the wordpress plugin support section at:

https://wordpress.org/support/topic/series-meta-information-being-displayed-twice-only-on-the-series-archive-pages/

**Comment by nerrad** [comment]
Thanks for reporting this.  Organize Series hooks into excerpts and content.  Usually when this happens it's because there's something unique happening in a theme and the way it outputs the content.

One thing you can try doing is in the Organize Series options page look for the `Series Meta (with excerpts):` field and delete the content of that field and then save the options.  That will mean that the series meta strip should _only_ show with full post content (but depending on your theme, it _may_ also mean that no series meta strip shows on the series archive page.

**Comment by Andy0708** [comment]
@nerrad 

What exactly does this mean?

> Usually when this happens it's because there's something unique happening in a theme and the way it outputs the content.

I am facing the same problem, and I am experiencing this with two different themes, one of which is my own simple theme. In both cases, the code is outputting the excerpt within the post list with `<?php the_excerpt(); ?>` - absolutely nothing out of the ordinary.

Is there any way to get around this? The above approach does not work because the text is included in the excerpt itself and therefore within `%postcontent%`. I have been battling this for a little while now and cannot seem to figure out how to get rid of the text within the excerpt itself.

Just to be clear, what happens is the following:

For the "Series Meta (with excerpts)" option, I have the following:

`<div class="seriesmeta">This entry is part %series_part% of %total_posts_in_series% in the series %series_title_linked%</div>%postcontent%`

The output is the `div` from above with the text. However, in place of `%postcontent%`, the text "This entry is part 3 of 3 in the series X" is prepended to the actual excerpt. This means that the series text is essentially output twice. I have tried to dump the contents of `get_the_excerpt()`, and that contains the series text, which appears to be the problem.

The **only** thing my theme does in regards to excerpts, is to output them using `the_exercept()`. That's it. Unfortunately that contains the series text as well.

Any help would be appreciated.

**Comment by nerrad** [comment]
Does the content of the posts on your site have content in the excerpt field for the post, or is it just using the first part of the `post_content`?

Why this matters is because when `the_excerpt()` is called and there is *no* content in the `post_excerpt` field for that post, then WordPress automatically calls `get_the_content` for that post which gets the value for the `post_content` field.  This in turn has anything hooked into `the_content` filter executed.  Organize Series hooks its series_meta strip into both `the_excerpt` and `the_content` filters which is why that is a condition that will show both meta strips.  There's some code also added to organize series to attempt removing its `the_content` filter the excerpt is being called but it doesn't always work (and why this ticket is open to work on improving that).

In the meantime, IF your theme is using `the_excerpt` and you do not actually have content in the _post_excerpt_ field for your posts, you can either try what I mentioned earlier which means you'd end up with something like this:

![screenshot of settings example](https://www.evernote.com/l/AAMANvFON0dNcLddZy_jXbbAuYghF4sAxuMB/image.png)

Or you can add content to your _post_excerpt_ fields and that will prevent WordPress from auto-generating an excerpt from the full `post_content` field.

**Comment by nerrad** [comment]
While typing my reply I noticed a bug with the code that's supposed to remove the callback on `the_content` filter in this situation.  If either of you want to try installing this to see if it fixes your issue (just install master), or you can take a look at the fix and just add it directly to the same file on your install you can see if it works for you.

**Comment by Andy0708** [comment]
Thank you so much for the detailed and quick reply, @nerrad. I have just tested out the above fix, and it does fix the issue. After adding the priority, everything now works as I expected in the first place. Thanks! 👍

**Comment by nerrad** [comment]
Thanks for getting back to me with the results from your testing.  This should show up in the next release then :)
