### ISSUE TITLE
Unlisted Series has been added to the list ?

### ISSUE THREAD

**Issue by KienNguyen1991** [roughsmoothengine/organize-series#55]
I'm having a very nasty mistake. May you support me.

I added a new tag in the Manage Series: "Hướng dẫn sử dụng LaTex"
https://imgur.com/NIJg4My

But when I create a new Post, it does not appear to be selected:
https://imgur.com/nRObLx4

I hope you support, I have reset the plugin but still not. Thank you!

**Comment by nerrad** [comment]
Thanks for the report.  I'll look into it when I get a chance.

**Comment by nerrad** [comment]
Sorry for the delay in getting back to you.  On the surface, from looking at your screenshots it appears that you are expecting new created series via the Manage Series page to be automatically selected when creating a new post.  If so, this is not the case and you still need to select the series you want a post to belong to after creating the post.

If my understanding of this issue is not correct, feel free to re-open this issue to add more details.  It's very important for bugs that you give clear, reproducible steps for replicating the bug - otherwise I can't be much help in fixing it.
